//
// Created by sr9000 on 21/12/2020.
//

#ifndef CMAKE_TINYPROXY_FILTER_POLICY_H
#define CMAKE_TINYPROXY_FILTER_POLICY_H

typedef enum
{
  FILTER_WHITE_LIST,
  FILTER_BLACK_LIST
} filter_policy_t;

#endif // CMAKE_TINYPROXY_FILTER_POLICY_H
